### PR TITLE
Changed text to "Total hodlings"

### PR DESCRIPTION
**Pull request by gianlucag**

### CODE REVIEW

**Comment by gianlucag** [comment]
You know, for hodlers...

**Comment by nrenich** [comment]
Can this be made an option to enable if you want it? I love a good meme as the next redditor but not all the time. Maybe in the .ini file, like hodlings=1 or something. Unless specified, default is 0.

**Comment by huwwp** [comment]
Yeah probs not, feel free to fork!

**Comment by gianlucag** [comment]
ooooooook, no prob.. I was just thinking it could have been a nice touch to get closer to the community, a real wallet for hodlers.. :-)

**Pull request closed without merging**
