### PR TITLE
Fix sort. Add action to change sort column.

### PR DESCRIPTION
**Pull request by talisein**

### CODE REVIEW

**Comment by talisein** [comment]
This is probably really ugly to anyone that knows python, but its an improvement

**Comment by ShaunHoyes** [comment]
I tried this out, and it seems to work for me. Your PR would make sorting default to the 'Val' column?

**Comment by talisein** [comment]
Yes. Val makes more sense to me to default to; I might hold 10,000 ripple but be totally uninterested in having it at the top.

**Comment by huwwp** [comment]
Looks good, thanks

**Pull request merged**
