### PR TITLE
Feature/async update

### LINKED ISSUE #21: High CPU use (low performance)
I didn't review the code but the CPU is highly used by python3 when the script is running. 

Br

### PR DESCRIPTION
**Pull request by juanjux**
- Uses a Timer thread to get the prices and update the screen
- Adds a config option for the time between updates
- Removes the need for requests_cache dependency
- Lowers CPU usage from 100% to minimal while reducing time between updates
- Other minor changes

Fixes #21

### CODE REVIEW

**Comment by huwwp** [comment]
I need a little more time to go over this, I'll merge it in soon likely, I'm learning a lot thanks

**Comment by juanjux** [comment]
I'll rebase it so it doesn't conflict.

**Comment by juanjux** [comment]
Rebased, now it shouldn't conflict with `~master` anymore.

**Comment by huwwp** [comment]
I had some intermittent errors while testing inputting under this branch

2017-08-01-202051_768x545_scrot

**Comment by juanjux** [comment]
Mmmmm, could you explain the problem? I've been using it all day without problems.

**Comment by huwwp** [comment]
I merged this then rolled back, it had issues with resizing the windows causing a crash, I think removing the innner loop caused it, I'll take another look later

**Comment by juanjux** [comment]
I will torture it later to try to reproduce this. Probably related to update the TUI in the timer thread, I'll move to a data fetching-only thread and a update in the loop.

**Pull request merged**
